name: sample-dockerfile-fastcgi-perl
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: digitalocean/sample-dockerfile-fastcgi-perl
  name: sample-dockerfile-fastcgi-perl
